version: 2
updates:
- directory: "/"
  package-ecosystem: "docker"
  schedule:
    interval: "daily"
  assignees:
  - "georgettica"
- directory: "/"
  labels:
  - "dependency"
  - "merge when passing"
  package-ecosystem: "github-actions"
  schedule:
    interval: "daily"
  assignees:
  - "georgettica"
- package-ecosystem: "gomod"
  directory: "/"
  labels:
  - "dependency"
  schedule:
    interval: "daily"
  assignees:
  - "georgettica"
